# Generated by Django 5.1.3 on 2024-11-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radicalConnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_skills', models.CharField(help_text='Select up to 3 skills', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='selected_skills',
        ),
    ]
