# Generated by Django 5.1.3 on 2024-12-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radicalConnect', '0005_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Create',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
